spring:
  application:
    name: simpleapp

  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:simpleappDB

logging:
  level:
    root: INFO
    sql: DEBUG
    LukaszSz90.simpleapp: DEBUG

